### ISSUE TITLE
Error when updating to Angular 5 and CLI 1.5

### ISSUE THREAD

**Issue by rhinoandre** [Taranys/ng-selector#7]
I'm trying to update my project to Angular 5 and CLI 1.5 but I'm facing some issue due to the ng-selector build.
```
ERROR in ./node_modules/ng-selector/index.ts
[0] Module build failed: Error: C:\workspace\WatchGuard\pages\access-policy\node_modules\ng-selector\index.ts is not part of the compilation output. Please check the other error messages for details.
[0]     at AngularCompilerPlugin.getCompiledFile (C:\workspace\WatchGuard\pages\access-policy\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:624:23)
[0]     at plugin.done.then (C:\workspace\WatchGuard\pages\access-policy\node_modules\@ngtools\webpack\src\loader.js:467:39)
[0]     at process._tickCallback (internal/process/next_tick.js:109:7)
[0]  @ ./component/wg-access-policy/wg-access-policy.module.ts 11:0-47
[0]  @ ./src/$$_lazy_route_resource lazy
[0]  @ ./node_modules/@angular/core/esm5/core.js
[0]  @ ./src/main.ts
[0]  @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

I check the ng-selector folder on node_modules and I saw that it contains both the ts and js files.
I tried doing this workaround  [index.ts is not part of the compilation output](https://github.com/elliotforbes/ng-diff-match-patch/issues/24) after this my project starting build but angular breaks to load the ng-selector.

Could you update the angular and cli version? 
[How to Upgrade Angular 4 to Angular 5 Apps](https://vitalflux.com/how-to-upgrade-angular-4-to-angular-5)

**Comment by Orodan** [comment]
Hi @rhinoandre 

you are right, there is a problem with ng-selector and Angular 5. The fact is with the new version of Angular, it respects the typescript configuration found in tsconfig.json or similar files. Because of that, the ts files of ng-selector are no longer compiled, which provocs the error you found, and even including them explicitely does not fix the problem.

I will work on upgrading ng-selector as soon as possible, it should be done by the end of the week I think. We should no longer expose ts files, but only js files to not trigger any errors anymore.

As a temporary work around, you can take the 3 ts files of ng-selector which are :

- ng-selector.module.ts
- ng-selector.component.ts
- ng-selector.validator.ts

and put them directly in your application instead of importing them from your node_modules folder.
For example, you will not import our module like that anymore :
```
import { NgSelectorModule } from 'ng-selector';
```
but this way instead (depending on your app structure) :
```
import { NgSelectorModule } from './shared/ng-selector/ng-selector.module';
```

I am aware it's not ideal, but at least it will stop triggering an error because of our module, and during this time I will solve the problem.

**Comment by rhinoandre** [comment]
I will do this workaround.

Thx!

**Comment by flavio-henrique** [comment]
I am having the same issue any update about this?

**Comment by Taranys** [comment]
We're one it. I already create a branch to fix this issue but it only work with --aot flag. It doesn't work with JIT.

This issue comes from the way the project is compiled. I will change it completely to avoid this kind of error for any future angular release :)

**Comment by rhinoandre** [comment]
I'm glad to know it.

Thanks!

**Comment by Taranys** [comment]
If you want to try, we just deploy a new version `3.0.0-0`. It is an alpha release for angular 5.

Be aware that jquery and selectize are now a peer depedencies so you have to install then in addition with ng-selector: `npm i ng-selector jquery selectize @types/selectize`

**Comment by rhinoandre** [comment]
Oh thank very much I'll test it.

**Comment by Taranys** [comment]
I push a new version (3.0.0) on npm which correct the issue and improve drastically to size on the bundle.

Don't hesitate to read the README to be sure it is integrated correctly.
